version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run:
          name: Instalar dependencias
          command: npm install
      - persist_to_workspace:
          root: .
          paths:
            - .

  docker_build:
    docker:
      - image: circleci/docker:20.10
    steps:
      - checkout
      - attach_workspace:
          at: /home/circleci/project
      - run:
          name: Construir la imagen Docker
          command: docker build -t $DOCKERHUB_USERNAME/Nirvana03:latest .

      # Iniciar sesión en Docker Hub
      - run:
          name: Iniciar sesión en Docker Hub
          command: |
            echo $DOCKERHUB_PASSWORD | docker login --username $DOCKERHUB_USERNAME --password-stdin

      # Empujar la imagen a Docker Hub
      - run:
          name: Empujar la imagen a Docker Hub
          command: docker push $DOCKERHUB_USERNAME/simple-pipeline-project:latest

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - docker_build:
          requires:
            - build
